### ISSUE TITLE
Ideas for new repo name

### ISSUE THREAD

**Issue by jkim222383** [UBC-MDS/DSCI524_Grp13_coRPysprofiling#1]
**Note**: Lowercase letters only recommended, camel case (e.g. camelCase) acceptable. Hyphens/underscores/other special characters not allowed (e.g. snake_case).

Based on the list we can decide on a name that sticks. Please add your ideas to the list:
- textviz
- eta
- coRPys

**Comment by ssyayayy** [comment]
I'm thinking about something similar to `pandas-profiling`, such as `text-profiling`.

**Comment by eboylestanley** [comment]
Discussed as group, final name choice - coRPysprofiling
